apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  labels:
    weave.works/applied-layer: layer-1
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.18
  dependsOn:
  - name: cert-manager
  - name: external-secrets
  - name: metallb
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m0s
  targetNamespace: ingress-nginx
  upgrade:
    crds: CreateReplace
  values: {}
status: {}
