apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  labels:
    weave.works/applied-layer: layer-2
  name: prometheus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.11
  dependsOn:
  - name: weave-policy-agent
  - name: ingress-nginx
  - name: secrets-store-config
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m0s
  targetNamespace: prometheus
  upgrade:
    crds: CreateReplace
  values: {}
status: {}
