apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  labels:
    weave.works/applied-layer: layer-1
  name: secrets-store-config
  namespace: flux-system
spec:
  chart:
    spec:
      chart: secrets-store-config
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta2
        kind: HelmRepository
        name: weaveworks-charts
        namespace: flux-system
      version: 0.0.2
  dependsOn:
  - name: cert-manager
  - name: external-secrets
  - name: metallb
  install:
    crds: CreateReplace
    createNamespace: true
  interval: 1m0s
  targetNamespace: external-secrets
  upgrade:
    crds: CreateReplace
  values:
    clusterSecretStores:
      aws-secretmanager:
        provider:
          aws:
            auth:
              secretRef:
                accessKeyIDSecretRef:
                  key: access-key
                  name: awssm-secret
                  namespace: flux-system
                secretAccessKeySecretRef:
                  key: secret-access-key
                  name: awssm-secret
                  namespace: flux-system
            region: eu-central-1
            service: SecretsManager
status: {}
