apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    templates.weave.works/template-name: add-workspace
    templates.weave.works/template-namespace: default
    toolkit.fluxcd.io/tenant: team-h
  name: team-h
  namespace: team-h
  annotations:
    templates.weave.works/create-request: "{\"repository_url\":\"https://github.com/weavegitops/podinfo-app.git\",\"head_branch\":\"wge-create-branch-apa01b\",\"base_branch\":\"main\",\"title\":\"Create resource default/team-shared-host51-cluster27\",\"description\":\"This PR creates a add-workspace instance\",\"template_name\":\"add-workspace\",\"parameter_values\":{\"CLUSTER_NAME\":\"default/team-shared-host51-cluster27\",\"NAMESPACE\":\"team-h\"},\"commit_message\":\"Create add-workspace instance\",\"credentials\":{},\"template_namespace\":\"default\",\"template_kind\":\"GitOpsTemplate\"}"
    templates.weave.works/created-files: "{\"files\":[\"clusters/default/team-shared-host51-cluster27/tenants/team-h.yaml\"]}"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    templates.weave.works/template-name: add-workspace
    templates.weave.works/template-namespace: default
    toolkit.fluxcd.io/tenant: team-h
  name: kustomize-controller
  namespace: team-h

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  labels:
    templates.weave.works/template-name: add-workspace
    templates.weave.works/template-namespace: default
    toolkit.fluxcd.io/tenant: team-h
  name: team-h
  namespace: team-h
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:team-h:reconciler
- kind: ServiceAccount
  name: kustomize-controller
  namespace: team-h

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    templates.weave.works/template-name: add-workspace
    templates.weave.works/template-namespace: default
  name: team-h-team-role
  namespace: team-h
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - buckets
  - helmcharts
  - gitrepositories
  - helmrepositories
  - ocirepositories
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - pac.weave.works
  resources:
  - policies
  verbs:
  - watch
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
- apiGroups:
  - flagger.app
  resources:
  - canaries
  - metrictemplates
  verbs:
  - get
  - list
